### ISSUE TITLE
ping not working

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/opensesame#108]
I have in the config:
```
ping.enable = 1
```

Then I do:
```
sudo killall -SIGUSR1 opensesame
```

Expected: that I see some output in NC what is going on (ping).

Actual result: no output.

**Comment by fel115** [comment]
In my setup, it works. 

```toml
nextcloud.chat = "<token>"
nextcloud.chat.licht = "<token>"
nextcloud.chat.ping = "<token>"
nextcloud.chat.commands = "<token>"
nextcloud.user = "<user>"
nextcloud.pass = "<pass>"
nextcloud.url = "https://nextcloud.markus-raab.org/nextcloud"
nextcloud.format.datetime = "%d.%m.%Y %H:%M:%S"
nextcloud.format.time = "%H:%M:%S"
validator.user1 = "14, 15 ,13 ,15, 11, 15, 7, 15"
validator.user2 = "14, 12, 14, 15, 11, 15"
ping.enable = 1
```
