### ISSUE TITLE
spelling fixes

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/opensesame#64]
Let us use some spell checker. In PermaplanT we have in .pre-commit-config.yaml:

```
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        # Scan all .md files, exclude folders /meetings & /reports.
        files: ^(?!.*\/(meetings|reports)\/).*\.md$
        args: [-L crate]
        stages: [manual]
```
